### ISSUE TITLE
Keygen.inc generate MainText large data

### ISSUE THREAD

**Issue by Cale-Torino** [ElvisBlue/EDGE-Keygen-Template#1]
Hi there, thanks for this useful template.
I would like to find out if there is an automated way to generate the large data for the `MainText` var in `Keygen.inc`?

<img width="618" alt="image" src="https://github.com/ElvisBlue/EDGE-Keygen-Template/assets/52330180/1f85fc27-58fc-443d-a2f0-165443eacbfc">

---

<img width="796" alt="image" src="https://github.com/ElvisBlue/EDGE-Keygen-Template/assets/52330180/18225546-a238-434d-b54d-8258a13e81cd">

Thanks!

**Comment by ElvisBlue** [comment]
As far as I know there are no automated way. Sorry :(
